/*********************************************************************
* Filename: example_c.cmd *
* *
* Author: David M. Alter, Texas Instruments Inc. *
* *
* Last Modified: 03/14/01 *
* *
* Description: C code linker command file for LF2407 DSP. *
*********************************************************************/

MEMORY
{
	PAGE 0: /* Program Memory */
	VECS: org=00000h, len=00040h /* internal FLASH */
	FLASH:org=00044h, len=07FBCh /* internal FLASH length 32700 words */
	SARAM:org=08000h, len=00800h /* internal SARAM length 2048 words*/
/*	EXTPROG: org=08800h, len=07800h  external SRAM */
	
	PAGE 1: /* Data Memory */
	B2: org=00060h, len=00020h /* internal DARAM length 32 words */

/*	B0: org=00200h, len=00100h /* internal DARAM length 256 words */
/*	B1: org=00300h, len=00100h /* internal DARAM length 256 words */
	INT_RAM: org =00200h , len = 001FFh /*B0 and B1 Internal Ram */

	SARAM: org=00800h, len=00800h  /* internal SARAM length 2048 words
/*	EXTDATA: org=08000h, len=08000h  external SRAM */
}


/*	//SECTIONS CREATED BY C COMPILER
Program Memory is Page 0 , Data Memory is Page 1 .
For our IC,ROM is equivalent to Flash, and Ram is either SARAM, or B0,B1,B2 which are DARAM.
NAME			USED FOR				MEMORY TYPE				
.text:    		code					Program ROM	   					
.cinit:   		global inits			Program ROM
.const    		const int x=25;			Data ROM   
.switch   		for case stmts			Program ROM
.bss:     		variables    			Data RAM
.stack:   		for SP					Data RAM   
.sysmem   		heap, dynamic mem		Data RAM
.vectors   	    vectors					Program ROM
*/
	SECTIONS
{
	/* Sections generated by the C–compiler */
	.text: > FLASH PAGE 0 	/* initialized */
	.cinit: > FLASH PAGE 0  /* initialized */
	.const: > B2 PAGE 1  /* was B1  1.Changed by harsha to remove .bss allocation .Initialized Section */
	.switch: > FLASH PAGE 0 /* initialized */
	.bss: > SARAM PAGE 1  	/* was B1 PAGE 1.Changed by harsha to remove .bss allocation error. Uninitialized Section*/ 
	.stack: >  INT_RAM PAGE 1 /*unitialized*/
	.sysmem: > INT_RAM PAGE 1 /* uninitialized */

	/* Sections declared by the user */
	vectors: > VECS PAGE 0 /* initialized */
}